### PR TITLE
Add support for API version 1.5

### PR DESCRIPTION
**Pull request by centromere**

### CODE REVIEW

**Review by Silvanoc — APPROVED** [review]
LGTM

**Comment by Silvanoc** [comment]
@centromere thanks for your contribution!

**Comment by centromere** [comment]
You're welcome @Silvanoc. Will this change be published to [pypi](https://pypi.org/project/containerd/)?

**Comment by Silvanoc** [comment]
> You're welcome @Silvanoc. Will this change be published to [pypi](https://pypi.org/project/containerd/)?

The expectation was for this to happen automatically thanks to Github Workflows... But apparently we all forgot to update the workflow for 1.4 and 1.5 :slightly_smiling_face: I'll take care of it.

**Comment by Silvanoc** [comment]
> > You're welcome @Silvanoc. Will this change be published to [pypi](https://pypi.org/project/containerd/)?
> 
> The expectation was for this to happen automatically thanks to Github Workflows... But apparently we all forgot to update the workflow for 1.4 and 1.5  I'll take care of it.

Done! Successful run can be seen here: https://github.com/siemens/pycontainerd/runs/3475103467?check_suite_focus=true

@centromere you can get it now from https://pypi.org/project/containerd/1.5.1/

**Comment by centromere** [comment]
Thank you!

**Pull request merged**
